# Generated by Django 3.1.1 on 2022-02-28 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='friend', max_length=20)),
                ('coolflex', models.IntegerField(default=1, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.IntegerField(choices=[(0, 'Blank'), (1, 'Stripes')], default=0, max_length=1)),
                ('color_one', models.CharField(choices=[(0, 'Blank'), (1, 'Stripes')], default='RED', max_length=3)),
                ('color_two', models.CharField(choices=[(0, 'Blank'), (1, 'Stripes')], default='WHI', max_length=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coolflex.user')),
            ],
        ),
    ]
