# Generated by Django 3.1.1 on 2022-03-17 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coolflex', '0002_auto_20220314_1028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cooluser',
            options={'ordering': ['last_name']},
        ),
        migrations.AlterModelOptions(
            name='klasse',
            options={'ordering': ['navn']},
        ),
    ]
