# Generated by Django 3.1.1 on 2022-02-28 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coolflex', '0002_auto_20220228_0920'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CoolUser',
        ),
    ]
