# Generated by Django 3.1.1 on 2022-03-17 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coolflex', '0003_auto_20220317_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooluser',
            name='klasse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cooluser', to='coolflex.klasse'),
        ),
    ]
