# Generated by Django 3.1.1 on 2022-03-10 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coolflex', '0003_auto_20220228_0920'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataCoolBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooluser_id', models.IntegerField(max_length=20)),
                ('box_id', models.IntegerField(max_length=20)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Klasse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bokstav', models.CharField(default='A', max_length=1)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='cooluser',
            name='coolflex',
        ),
        migrations.AddField(
            model_name='cooluser',
            name='last_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='cooluser',
            name='first_name',
            field=models.CharField(default='CoolUser', max_length=20),
        ),
        migrations.DeleteModel(
            name='Design',
        ),
        migrations.AddField(
            model_name='cooluser',
            name='klasse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='coolflex.klasse'),
        ),
    ]
