# Generated by Django 3.1.1 on 2022-03-10 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coolflex', '0004_auto_20220310_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooluser',
            name='klasse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coolflex.klasse'),
        ),
    ]
