# Generated by Django 3.1.1 on 2022-03-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coolflex', '0005_auto_20220310_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='klasse',
            name='grade_number',
            field=models.IntegerField(default=1, max_length=1),
        ),
    ]
