# Generated by Django 3.1.1 on 2022-03-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coolflex', '0005_auto_20220321_1021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datacoolbox',
            options={'ordering': ['timestamp']},
        ),
        migrations.AddField(
            model_name='cooluser',
            name='status',
            field=models.CharField(blank=True, default='MIA', max_length=3, null=True),
        ),
    ]
