# Generated by Django 3.1.1 on 2022-03-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coolflex', '0006_auto_20220324_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooluser',
            name='status',
            field=models.CharField(blank=True, default='DEF', max_length=3, null=True),
        ),
    ]
